# Hyperparameters for a 1-block CNN
[cnn]
batchsize   = 64
shuffle     = true
device      = "gpu"
kernelsize  = 20
epochs      = 100
train_frac  = 0.8
k           = 0

"σ"         = "relu"
maxpool     = 2
"η"         = 0.001
momentum    = 0.9

# One conv block + one dense head
dropouts    = [0.2, 0.5]   # conv block dropout, dense head dropout
layerouts   = [32]         # single conv block with 32 filters
