[sample]
# Target sequence length
seqlen = 75

# Random seed for reproducibility
seed = 42

# Directory containing FASTA files
datadir = "data/fasta"

# Paths to modern and ancient FASTA files
modern  = "data/fasta/French_chr3_75nt.fasta"
ancient = "data/fasta/Neandertal_chr3_75nt.fasta"
